##TASK-1

In [1]:
import numpy as np

In [4]:
#1
arr = np.diag([9,9,9])
print(arr)

[[9 0 0]
 [0 9 0]
 [0 0 9]]


In [11]:
#2
arr = np.arange(2,34,2).reshape(4,4)
print(arr)
avg = arr.mean()
std = arr.std()
res = arr[(arr >= avg-0.5*std)&(arr <= avg+0.5*std)]

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


In [13]:
#the values that are within 1/2 standard deviations of the mean.
print(res)

[14 16 18 20]


In [14]:
#3
arr = np.zeros((9,9), dtype=int)
print(arr)

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


In [21]:
#4
n = int(input("Enter n: "))
arr = (np.ones((n,1))*np.arange(1, n+1)).astype(int)
print(arr)

Enter n: 5
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
